version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "translate-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19exmw18co14"
s3_prefix = "translate-api"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
