AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  translate-api

  Sample SAM Template for translate-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180

Resources:
  TranslateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/translate/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      Policies:
        - TranslateReadOnly
      Environment:
        Variables:
          CHARACTER_COUNT_SUM_LIMIT: 490000
      Events:
        Translate:
          Type: HttpApi
          Properties:
            Path: /translate
            Method: get
            TimeoutInMillis: 29000

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TranslateApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  HelloWorldFunction:
    Description: "Translate Lambda Function ARN"
    Value: !GetAtt TranslateFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Translate function"
    Value: !GetAtt TranslateFunctionRole.Arn
